<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Effanville.FPD.Logic</RootNamespace>
    <AssemblyName>Effanville.FPD.Logic</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetProjects.WpfToolkit.DataVisualization" Version="6.1.94" />
    <PackageReference Include="System.IO.Abstractions" Version="22.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FinancialStructures\Common\src\Common.UI\Common.UI.csproj" />
    <ProjectReference Include="..\..\FinancialStructures\src\FinancialStructures\FinancialStructures.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TemplatesAndStyles\" />
  </ItemGroup>

</Project>